### ISSUE TITLE
It just doesn't work. Maybe I am doing something wrong?

### ISSUE THREAD

**Issue by ibobak** [anthonyattard/zoomer#7]
Version v0.2.3  is installed in VS code 1.88.1

In settings I see  
"customWindowZoom.zoomLevelChangeValue": 0.1

however, when I press Ctrl =  and Ctrl Numpad minus,  I see the same "jumping" on huge percentage as it was before.
Vs code was restarted.

what I am doing wrong?

**Comment by anthonyattard** [comment]
Hello Ihor, thanks for bringing this to my attention. Can you let me know which OS you are running? 

The plugin currently only works with the regular plus and minus keys, not the numpad. Can you confirm if the non numpad keys for increase and decrease work? If it does I will add the numpad compatability to a future version after testing.

**Comment by ibobak** [comment]
I am on Ubuntu 22.04

When I press Ctrl +,  I will get from this one
![image](https://github.com/anthonyattard/zoomer/assets/8807043/12838993-2371-4345-9c71-04bcd0a3d6a7)
to this one
![image](https://github.com/anthonyattard/zoomer/assets/8807043/728375c2-a06c-4732-8223-610804528738)

And that is really a big difference - much bigger than I would press Ctrl Shift +

**Comment by ibobak** [comment]
But it seems I've found what was the source of the problem:
![image](https://github.com/anthonyattard/zoomer/assets/8807043/ce539f8f-6f3a-4ee1-96f9-6a805a642295)


as soon as I removed keybindings from  "View: zoom in" and "View: zoom out"   and assigned new ones to zoomer
![image](https://github.com/anthonyattard/zoomer/assets/8807043/1542e673-dcec-47ba-b785-f59293731e8d)

everything works now.

**Comment by ibobak** [comment]
As I understand,   when I was pressing  Ctrl =,   both actions (the default one and zoomer's one) were executed at the same time.

**Comment by anthonyattard** [comment]
Thanks for spotting this, the latest version 0.3.1 has added numpad support. [v0.3.1](https://github.com/anthonyattard/zoomer/releases/tag/v0.3.1)
